### ISSUE TITLE
InstallBIOS

### ISSUE THREAD

**Issue by hbeatty** [hbeatty/iDRAC-Ansible-module#10]
This will not work if you need to do a stepping upgrade.

These aren't proper versions. Just an example.

```
- hosts:
   - edge
   - mid
  gather_facts: False
  sudo: yes

  tasks:
    - name: Install BIOS 1.3.0
      local_action:
        module: idrac
        username: "{{lom_user}}"
        password: "{{lom_pass}}"
        hostname: "{{lom_hostname}}"
        command: "InstallBIOS"
        firmware:
          url: "http://server.example.com/firmware/BIOS_YKH49_WN64_1.3.0.EXE"
          identity_info_value: "DCIM:BIOS:159"
          target_version: "1.3.0"
          reboot: "True"

    - name: Install BIOS 1.3.6
      local_action:
        module: idrac
        username: "{{lom_user}}"
        password: "{{lom_pass}}"
        hostname: "{{lom_hostname}}"
        command: "InstallBIOS"
        firmware:
          url: "http://server.example.com/firmware/BIOS_YKH49_WN64_1.3.6.EXE"
          identity_info_value: "DCIM:BIOS:159"
          minimum_version: "1.3.0"
          target_version: "1.3.6"
          reboot: "True"

    - name: Install BIOS 1.3.8
      local_action:
        module: idrac
        username: "{{lom_user}}"
        password: "{{lom_pass}}"
        hostname: "{{lom_hostname}}"
        command: "InstallBIOS"
        firmware:
          url: "http://server.example.com/firmware/BIOS_YKH49_WN64_1.3.8.EXE"
          identity_info_value: "DCIM:BIOS:159"
          target_version: "1.3.8"
          minimum_version: "1.3.6"
          reboot: "True"

```

Change this to UpgradeBIOS and add a rollback function
